### ISSUE TITLE
Release weights of pretrained models or model prediction 

### ISSUE THREAD

**Issue by rashidch** [HRHLALALA/next-prediction-pytorch#1]
Hi,

Can you release the weights of pretrained model in pytorch or prediction of that model for visualization?

Thank You.

**Comment by HRHLALALA** [comment]
Hi, thanks for your interest! I plan to replicate it and upload new checkpoints later this year.

**Comment by rashidch** [comment]
Hi, Do you mean that you do not have checkpoints for pretrained models using PyTorch?

**Comment by HRHLALALA** [comment]
> Hi, Do you mean that you do not have checkpoints for pretrained models using PyTorch?

No. Just need some time to check the records on my computer.

Please see the [here](https://www.dropbox.com/scl/fi/vl9xvtpi1cg30p4640r7q/next-models.zip?rlkey=nvh02nokdajehqgziop71vo97&dl=0)
